version = "1.0"

[main]
name.en = "Configuration panel"
name.fr = "Panneau de configuration"
services = ["__APP__"]

[main.uploads]
name.en = "Upload limit size"
name.fr = "Téléchargement de fichiers"

  [main.uploads.max_upload_size]
      ask.fr = "Taille limite pour le téléchargement des fichiers en Mo"
      ask.en = "Size limit file upload (Mb)"
      type = "number"
      min = 0
      max = 5000
      help.fr = "Valeur maximale de 5Go"
      help.en = "Max size 5Gb"
      bind = "VITE_UPLOAD_LIMIT:__INSTALL_DIR__/.env"
